# Generated by Django 2.0.2 on 2018-03-06 13:27

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.FileField(upload_to=home.models.invoice_file),
        ),
    ]
